### ISSUE TITLE
[Feature request] Frame buffers

### ISSUE THREAD

**Issue by Zinggi** [elm-community/webgl#35]
It's currently impossible to perform certain rendering operation common in many 3d games.
Many techniques require rendering to a texture (or other types of a frameBuffer).

Examples include:
  * Post-processing / FXAA / mirrors / realtime reflections / cameras
    * **general info** [here](https://open.gl/framebuffers) and [here](https://learnopengl.com/#!Advanced-OpenGL/Framebuffers)
  * [Shadow mapping](https://learnopengl.com/#!Advanced-Lighting/Shadows/Shadow-Mapping) / [SSAO](https://learnopengl.com/#!Advanced-Lighting/SSAO)
  * [Deferred shading](https://learnopengl.com/#!Advanced-Lighting/Deferred-Shading)
  * [Physically based rendering](https://learnopengl.com/#!PBR/Theory)

For the API, I propose a counterpart to `toHtml` and `toHtmlWith`, but instead of rendering to `Html`, it should render to a `Texture`.
E.g.
```elm
renderToTextureWithSettings : RenderToTextureOptions -> List Renderable -> Texture
```

Where `RenderToTextureOptions` would be something like:
```elm
type alias RenderToTextureOptions =
  { width : Float
  , height : Float
  , settings : List Setting
  }
```

I didn't fully think that api through, it's just a suggestion.

**Comment by w0rm** [comment]
I guess it is quite possible to do it like this. From the runtime side, `renderToTextureWithSettings`  can return a thunk function, that will be evaluated with the `WebGLContext` when the uniform is initiated.

**Comment by w0rm** [comment]
I have a (kinda) working POC here: https://github.com/elm-community/webgl/tree/render-to-texture

**Comment by koenusz** [comment]
I think a nice addition to this feature would be to add a function to the Texture to get the color at a position. This way the texture can be used for picking functionality.

**Comment by w0rm** [comment]
@koenusz render to texture won't create an image that may be used for picking. It will only encapsulate the instructions of how to render to texture. We need the `gl` context and we can only access it when the virtual dom node is rendered.

**Comment by shamansir** [comment]
Would be nice also to be able to do things like in this article https://webglfundamentals.org/webgl/lessons/webgl-render-to-texture.html, for making different kinds of reflections & s.o. Just saying.

**Comment by guydunton** [comment]
Has there been any progress on this feature? I wanted to port some C++ code (demo [here](https://youtu.be/J7V02FZv3tA)) to Elm but it requires render to texture to implement the deferred shading. Is there any way to help this along?

**Comment by w0rm** [comment]
@gdunton no progress so far apart from https://github.com/elm-community/webgl/tree/render-to-texture branch.

The API there looks nice and simple, because it is similar to the `toHml` function. 

```elm
fromEntities : Options -> ( Int, Int ) -> List WebGL.Entity -> Result Error Texture
fromEntities { magnify, minify, horizontalWrap, verticalWrap, flipY } ( width, height ) entities =
```

However there are problems with this solution:

1. In many cases we need to render to a texture on every frame. The current draft implementation would create a new texture and a frame buffer each time. That is really slow to do on each frame. Ideally we need a way to reuse the frame buffers, but this is hard with the declarative api.
2. The data is cached forever, meaning dynamically creating textures grows the memory.

What we need is to invent some cache control from the declarative api.

**Comment by guydunton** [comment]
@w0rm That's unfortunate but makes sense. Having thought about it for a bit I can't think of a place to cache the frame buffers that doesn't limit what can be done with the api.
- If the buffer is cached in the entity creating it, it cannot be used in multiple other buffers.
- If the buffer is cached in the entity consuming it, the consuming entity can only use a single buffer.
- Caching the buffer in a texture forces the coder to store it in a model which moves away from the declarative api.

It seems that the programmer needs more control over buffers and could be required to store the texture in their model to achieve this; although that isn't particularly clean. Sorry if this isn't very helpful.

**Comment by w0rm** [comment]
@gdunton There is no way to cache buffers in either textures or entities, because a buffer is bound to the gl context which is stored in the virtual dom node. The same texture may be sent to different canvases.

The way it currently works is each texture gets a new unique id that is used to store the texture in the cache that is attached to the virtual dom node. The texture is cached once it is accessed from the uniforms and it is cached forever.

With rendering to textures we need to reuse the frame buffer between multiple textures. But we need to do it in a clever way. Some of the buffers may need to be reused on each render and others may be needed to be cached forever.

What would be the way to control the cache? How can we tell if a particular frame buffer may be reused? It should probably have the same dimensions and texture options.
What should we do with buffers from multiple recursive textures? E.g. when a scene and a texture require another rendered texture. In this case we would need two buffers.

**Comment by guydunton** [comment]
@w0rm I'm not sure whether this would suite all needs but as the simplest,hacky solution you could alter Option to
```elm
type alias Options =
    { magnify : Resize Bigger
    , minify : Resize Smaller
    , horizontalWrap : Wrap
    , verticalWrap : Wrap
    , flipY : Bool
    , bufferName : Maybe String
    }
```
defaultOptions could provide Nothing while a user could name the buffer. This would let you cache the buffer in a map in the virtual dom node, that way the user could choose whether they wanted to render to a specific buffer or not. I've been trying to think of a slightly more elegant solution other than strings but I'm drawing a blank.

**Comment by w0rm** [comment]
@gdunton I thought about providing keys for the cache. But how would this work if the same buffer name is used for two textures that have different sizes?

**Comment by w0rm** [comment]
I had another idea, what if we could do smth like this:

```elm
frameBuffer : Options -> ( Int, Int ) -> Result Error FrameBuffer

fromEntities : FrameBuffer -> List Entity -> Texture
```

Each frame buffer gets its id and is cached. So it would be possible to create it separately outside the view function, or store in the model, and reuse for rendering.

One problem I see in this solution is when a frame buffer is used multiple times in the rendering tree. I guess we should store multiple of them under the same cache id and then reuse.

Another problem is supporting only-render-once cases, when we just need to render to a texture and cache it forever without re-evaluating. I guess in this case we should give an id to the texture and store it for the frame buffer, so that the frame buffer would check if the last rendered id matches the one from the texture, then it should not do anything.

**Comment by guydunton** [comment]
I like the idea of a new type for the FrameBuffer and following from that I have been toying with this:
```elm
type alias BufferedTexture =
    { buffer : FrameBuffer
    , texture : Texture
    }

renderIntoBuffer : FrameBuffer -> List entity -> BufferedTexture
renderIntoBuffer buffer entities =
    BufferedTexture buffer 3

overwriteBufferedTexture : BufferedTexture -> List entity -> BufferedTexture
overwriteBufferedTexture bufferedTexture entities =
    bufferedTexture

deconstructBufferedTexture : BufferedTexture -> ( FrameBuffer, Texture )
deconstructBufferedTexture bufferedTexture =
    ( bufferedTexture.buffer, bufferedTexture.texture )
```

The names aren't very good but this would allow the programmer to decide how they wanted to render into the buffers. The BufferedTexture could be deconstructed to allow the texture to be stored (perhaps in the model) while the buffer could be reused. If the program required the buffer to be rendered into each frame and the old texture wasn't required it could be overwritten.

This still doesn't solve the buffer being used multiple times in the rendering tree however.

**Comment by w0rm** [comment]
@gdunton I'm not sure why these things are needed. 

`fromEntities` produces a `Texture` with a certain id (under the hood it just stores the instructions needed to evaluate the texture). This texture is rendered onto the corresponding frame buffer when evaluated. That frame buffer should be defined outside the view function & cached, just like a mesh. If a user is calling `fromEntities` with the same buffer multiple times, then the texture inside this buffer will be overridden on every frame, and the buffer will be reused, just what we want!

Now, if we want to only render once, what we do, is remember an id of the last texture that was rendered into the certain frame buffer. If this id is the same, then we should not replace the contents of the frame buffer. So in order to preserve a texture, a user has to store it somewhere in the model or define as a constant in the top level scope.

**Comment by guydunton** [comment]
@w0rm That all makes sense to me. I was suggesting those new functions to allow the user more explicit controls of buffers and textures but it makes less sense to add them if you don’t need to.

**Comment by w0rm** [comment]
@gdunton I think I managed to make it work in the https://github.com/elm-community/webgl/tree/render-to-texture branch. Would be good if more people checked that this actually works. You can clone this branch and write code in the examples folder. The current example in `render-to-texture.elm` just renders a simple gradient onto the texture, and then renders it again on the rotating rectangle.

**Comment by w0rm** [comment]
I modified the example to render the crate scene onto the texture and then render the result texture onto the rotating square. Seems to be working fine! And the frame buffer is properly cached.

![untitled](https://user-images.githubusercontent.com/43472/37617203-ae8e9d80-2bb2-11e8-9853-f83d48e2c3bc.gif)

**Comment by ajlende** [comment]
I've been waiting for the ability to do multi-pass stuff for a while now—thanks for working on this! I did a quick [gaussian blur example](https://github.com/ajlende/webgl/blob/render-to-texture/examples/blur.elm). It's mostly working—I haven't tried to get the reflection fixed yet.

![gaussian blur example animation](https://user-images.githubusercontent.com/5129775/37632248-598bb8c8-2bbb-11e8-83bf-a013503f4d64.gif)

**Comment by w0rm** [comment]
@ajlende there is a problem, `gl.clear` doesn’t seem to clean up the stencil buffer in the frame buffer. Even though it should here: https://github.com/ajlende/webgl/blob/render-to-texture/src/Native/WebGL.js#L380

**Comment by guydunton** [comment]
@w0rm I've been playing with this in an example and it's exciting. However, I think I've discovered a bug with regards to passing multiple textures into a shader. 

Here: https://github.com/gdunton/webgl/blob/7d58ce9d42f54b3fcd05b0c39ab3b2a4404e9dba/examples/deferred-shading.elm#L307
& here: https://github.com/gdunton/webgl/blob/7d58ce9d42f54b3fcd05b0c39ab3b2a4404e9dba/examples/deferred-shading.elm#L470

I'm not exactly sure what's happening but swapping around the textures in the record causes the other texture to be all white.

**Comment by w0rm** [comment]
@gdunton thanks for trying this! Could you reduce the example to a minimum? 

In any case please keep the code, I will try to fix the issue.

**Comment by guydunton** [comment]
@w0rm I've created an example showing the error with multiple textures being passed into a shader to combine them. The color on screen should be yellow because the combined shader adds together a red texture and a green texture, but the output is green. 

If the order of the parameters into the combine shader are swapped then the output is always the second texture.

https://github.com/gdunton/webgl/blob/render-to-texture/examples/combine-buffers.elm

I've also tried passing multiple textures into a single shader and this works correctly.

**Comment by w0rm** [comment]
@gdunton thanks! I pushed the fix. I made a stupid JavaScript mistake.

Unfortunately programming in JavaScript after work is not as easy as Elm!

**Comment by w0rm** [comment]
@gdunton I wonder if this new API looks intuitive and allows you to implement your demo?

**Comment by guydunton** [comment]
@w0rm I've been working on it and I'm enjoying the API, especially because Maybe Framebuffer can separated from the use, not having to deal with maybe's in the pipeline is helpful.
I'm just having some trouble porting to webGL because I can't use signed image data, that’s more of a webGL 2 thing though I think. I'm pretty sure I'll be able to do it with the current API but I'm having to remember a lot of maths that I'd forgotten!

**Comment by w0rm** [comment]
@gdunton the reason `frameBuffer` returns `Result` is because we're using the same `Options` as for loading a `Texture` from a file. It fails when the dimensions are not power of two and mipmapping is enabled.

**Comment by w0rm** [comment]
@ajlende I had the same issue with the stencil buffer when rendering this scene [with a headless gl](https://github.com/stackgl/headless-gl/issues/97). The issue can be mitigated by clearing the stencil buffer. You just render the same floor with settings that don't put it on the screen, but clear the stencil bits.

Appending this in the end of entities does the work by failing the stencil test and emptying the stencil buffer when it fails:

```
    , WebGL.entityWith
        [ StencilTest.test
            { ref = 1
            , mask = 1
            , test = StencilTest.never
            , fail = StencilTest.zero
            , zfail = StencilTest.keep
            , zpass = StencilTest.keep
            , writeMask = 0xFF
            }
        ]
        floorVertex
        floorFragment
        floorMesh
        { texture = texture
        , perspective = camera
        }
```

This screencast below renders the crate scene on the sides of the rotating cube:

![untitled](https://user-images.githubusercontent.com/43472/37869668-13ddc7e4-2fbc-11e8-8447-973aa0915d8b.gif)

cc @shamansir this looks like the demo from your link ^

**Comment by ajlende** [comment]
@w0rm I was also able to [get it to work](https://github.com/ajlende/webgl/commit/e58c6021e8e74adced8b0ed6da3557730e98998a) by adding `gl.stencilMask(0xFF)` right before the `gl.clear` call that you pointed out because apparently it needs to be enabled in order to clear it.

[How to clear the stencil buffer](https://www.opengl.org/discussion_boards/showthread.php/125865-How-to-clear-stencil-buffer-after-stencil-test)
[Depth test & stencils - Planar reflections](https://open.gl/depthstencils#Planarreflections)

**Comment by w0rm** [comment]
@ajlende oh, I see, didn't know that it depends on the mask. We probably need to restore the mask value when we remove the stencil setting  https://github.com/elm-community/webgl/blob/master/src/Native/WebGL.js#L126

**Comment by w0rm** [comment]
@ajlende I pushed a proper fix to the same branch. I figured out how to get the default value for the stencil mask, because different platforms may have different number of stencil bits. https://github.com/elm-community/webgl/commit/245d2fd557cadd40ae01da5819d487dfdc12ba05

Apparently there was the same issue with the depth mask. I fixed it too.

**Comment by w0rm** [comment]
To test that multiple steps work, I rendered the crate scene onto a texture, then rendered a cube with that texture onto another texture, and then rendered a cube with the final texture. Works fine!

![screen shot 2018-03-27 at 21 17 21](https://user-images.githubusercontent.com/43472/37989690-7aa30706-3204-11e8-8026-cd1a0f096857.png)

**Comment by guydunton** [comment]
@w0rm I've worked some more on deferred rendering and I've managed to get something working. The code is a mess but it seems to work well.

![elm webgl](https://user-images.githubusercontent.com/14931831/38165553-38c74db8-350d-11e8-9d66-b22496ba5f88.gif)

There are some hoops that need to be jumped through but these are limitations of WebGL 1.0 rather than the elm implementation.

**Comment by w0rm** [comment]
This feature was re-requested in the new repo: https://github.com/elm-explorations/webgl/issues/6
