### ISSUE TITLE
Create textures procedurally

### ISSUE THREAD

**Issue by milibopp** [elm-community/webgl#55]
Provided I understand the current API correctly, there is currently no way to create a texture programatically by providing the color values as data to some constructor. Is this intentional?

I kind of have a use case for procedural textures, namely converting colormaps into textures on the fly. If this is a desired feature, I might be interested in implementing it.

**Comment by w0rm** [comment]
@aepsil0n correct, there is no API in the Elm platform that allows to work with binary data. 

You can do work in JS and then send a [Blob URL](https://developer.mozilla.org/en-US/docs/Web/API/Blob#Example_for_creating_a_URL_to_a_typed_array_using_a_blob) through a port and use it to load as a Texture.

There is also this package https://github.com/justgook/elm-image-encode that allows to encode an image into a base64 encoded URL, that is also possible to load as a Texture.

Hopefully any of these two solutions would work for your case. Happy to discuss this in the webgl channel in Elm slack.

I'm closing the issue here because the 0.19 version has been moved here: https://github.com/elm-explorations/webgl

**Comment by milibopp** [comment]
Thanks for the tips. This might actually work, I have to give it a try.
