### ISSUE TITLE
Elm 0.19 - Are we able to upgrade?

### ISSUE THREAD

**Issue by JordyMoos** [elm-community/webgl#58]
Elm 0.19 came out and know I'm wondering if I would be able to upgrade a project that relies on this library. Because I see you have native code.

Hopefully there is a way and if so I would like to offer my help.

**Comment by ajlende** [comment]
webgl is one of the few packages that's been approved to use what is now being referred to as "kernel code" (instead of "native code").

You can now find it under [elm-explorations](https://github.com/elm-explorations) as [elm-explorations/webgl](https://github.com/elm-explorations/webgl). [linear-algebra](https://github.com/elm-explorations/linear-algebra) has moved under elm-explorations also.

**Comment by JordyMoos** [comment]
Thanks @ajlende

**Comment by w0rm** [comment]
@JordyMoos Thanks for raising this issue, I added a deprecation notice.
